"""empty message

Revision ID: 8642f224c1c3
Revises: c17feda06631
Create Date: 2021-06-10 01:22:51.981122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8642f224c1c3'
down_revision = 'c17feda06631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('property')
    # op.drop_table('productimage')
    # op.drop_table('propertyvalue')
    # op.drop_constraint('fk_order_user', 'order', type_='foreignkey')
    # op.drop_constraint('fk_order_store', 'order', type_='foreignkey')
    # op.create_foreign_key(None, 'order', 'store', ['sid'], ['id'])
    # op.create_foreign_key(None, 'order', 'user', ['uid'], ['id'])
    # op.drop_constraint('fk_orderitem_product', 'orderitem', type_='foreignkey')
    # op.drop_constraint('fk_orderitem_order', 'orderitem', type_='foreignkey')
    # op.drop_constraint('fk_orderitem_user', 'orderitem', type_='foreignkey')
    # op.create_foreign_key(None, 'orderitem', 'product', ['pid'], ['id'])
    # op.create_foreign_key(None, 'orderitem', 'user', ['uid'], ['id'])
    # op.create_foreign_key(None, 'orderitem', 'order', ['oid'], ['id'])
    # op.drop_constraint('fk_product_store', 'product', type_='foreignkey')
    # op.drop_constraint('fk_product_category', 'product', type_='foreignkey')
    # op.create_foreign_key(None, 'product', 'category', ['cid'], ['id'])
    # op.create_foreign_key(None, 'product', 'store', ['sid'], ['id'])
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('fk_product_category', 'product', 'category', ['cid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('fk_product_store', 'product', 'store', ['sid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.create_foreign_key('fk_orderitem_user', 'orderitem', 'user', ['uid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('fk_orderitem_order', 'orderitem', 'order', ['oid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('fk_orderitem_product', 'orderitem', 'product', ['pid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('fk_order_store', 'order', 'store', ['sid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('fk_order_user', 'order', 'user', ['uid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_table('propertyvalue',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ptid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['product.id'], name='fk_propertyvalue_product', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ptid'], ['property.id'], name='fk_propertyvalue_property', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('productimage',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['product.id'], name='fk_productimage_product', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('property',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['category.id'], name='fk_property_category', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    # ### end Alembic commands ###
