"""empty message

Revision ID: cdbd1c23e0b6
Revises: 2d6c5fd6fba4
Create Date: 2021-06-10 14:22:40.101801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbd1c23e0b6'
down_revision = '2d6c5fd6fba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propertyvalue', type_='foreignkey')
    op.drop_constraint(None, 'propertyvalue', type_='foreignkey')
    op.create_foreign_key('fk_propertyvalue_property', 'propertyvalue', 'property', ['ptid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('fk_propertyvalue_product', 'propertyvalue', 'product', ['pid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.create_foreign_key('fk_property_category', 'property', 'category', ['cid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'productimage', type_='foreignkey')
    op.create_foreign_key('fk_productimage_product', 'productimage', 'product', ['pid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('fk_product_store', 'product', 'store', ['sid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('fk_product_category', 'product', 'category', ['cid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.create_foreign_key('fk_orderitem_product', 'orderitem', 'product', ['pid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('fk_orderitem_user', 'orderitem', 'user', ['uid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_index('fk_orderitem_order', 'orderitem', ['oid'], unique=False)
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('fk_order_user', 'order', 'user', ['uid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key('fk_order_store', 'order', 'store', ['sid'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    # ### end Alembic commands ###
